### ISSUE TITLE
Sybase support does not work with Sybase ASE 15.7

### ISSUE THREAD

**Issue by hakkika** [flyway/flyway#1220]
It seems that the SAP ASE support does not work on Sybase ASE 15.7:

$ ./flyway info
Flyway 4.0 by Boxfuse

Database: jdbc:sybase:Tds:127.0.1.1:5000/sybdb (Adaptive Server Enterprise 15.7)
ERROR: Unsupported Database: Adaptive Server Enterprise 15.7

Maybe the expected string in
flyway/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/DbSupportFactory.java
should be something else:

	//Sybase ASE support
        if (databaseProductName.startsWith("ASE")) {
        	return new SybaseASEDbSupport(connection);
        }

**Comment by axelfontaine** [comment]
Fixed with PR.

**Comment by seneiran** [comment]
Hey,i'm using flyway plugin with maven, i have tried several versions and currently the version 5.1 still having this issue.  Exists a way to force flyway the DB server? 

im using 
Sybase 15.7 (supported by Flyway) 
Flyway-maven-plugin v 5.1.0
JTDS 1.3.1

my connection string: 
[INFO] ------------------------------------------------------------------------
[INFO] Building flyway-mvn 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- flyway-maven-plugin:5.1.0:repair (default-cli) @ flyway-mvn ---
[INFO] Flyway Community Edition 5.1.0 by Boxfuse
[INFO] Database: jdbc:jtds:sybase://x.x.x.81:17000/database (sql server 12.50)


And the error im getting: 

Unsupported Database: sql server 12.50

i appreciate any support or guidance here. 

thanks in advance
