### ISSUE TITLE
SEVERE: Unexpected error java.lang.StringIndexOutOfBoundsException: start 0, end -3, length 16

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [flyway/flyway#3388]
###### Which version and edition of Flyway are you using?

8.4.4 docker file

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
GCP BigQuery dataset

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Running below will give error, while working from Google Cloud Console

```sql
CREATE TABLE IF NOT EXISTS `dataset_001.calendar`
(
  date DATE NOT NULL,
  description STRING,
  year INT64 NOT NULL,
  quarter INT64 NOT NULL,
  month INT64 NOT NULL,
  day INT64 NOT NULL,
  monthName STRING NOT NULL,
  monthOfQuarter INT64 NOT NULL,
  weekName STRING NOT NULL,
  isWeekend BOOL NOT NULL,
  weekOfYear INT64 NOT NULL,
  fiscalQuarter INT64 NOT NULL,
  fiscalYear INT64 NOT NULL,
  isTradingDay BOOL NOT NULL,
  isBankingDay BOOL NOT NULL,
  us STRUCT<isTradingDay BOOL NOT NULL, isBankingDay BOOL NOT NULL, isBusinessDay BOOL NOT NULL, prevTradingDay DATE, mtdTradingDays INT64, isMonthFirstTradingDay BOOL, isMonthLastTradingDay BOOL, description STRING> NOT NULL,
  ca STRUCT<isTradingDay BOOL NOT NULL, isBankingDay BOOL NOT NULL, isBusinessDay BOOL NOT NULL, prevTradingDay DATE, mtdTradingDays INT64, isMonthFirstTradingDay BOOL, isMonthLastTradingDay BOOL, description STRING> NOT NULL,
  mtdTradingDays INT64,
  custom ARRAY<STRUCT<name STRING NOT NULL, isBusinessDay BOOL NOT NULL, description STRING>>
)
PARTITION BY date
CLUSTER BY date;

CREATE OR REPLACE FUNCTION dataset_001.fn_incDate(p_date ANY TYPE, p_inc INT64, p_part STRING) RETURNS DATETIME
AS (
		 CASE WHEN p_part LIKE '%_d' THEN
				CASE WHEN ( p_inc > 0 ) THEN
						( SELECT date[SAFE_OFFSET( p_inc )]
							FROM (
									SELECT ARRAY_AGG ( date ORDER BY date ) AS date
									FROM dataset_001.calendar AS c
									WHERE date BETWEEN CAST ( p_date AS DATE ) AND DATE_ADD( CAST ( p_date AS DATE ), INTERVAL ( p_inc * 2 ) + 5 DAY )
										AND ( ( LOWER ( p_part ) = 'td' AND isTradingDay ) --trading days
											OR ( LOWER ( p_part ) = 'bd' AND isBankingDay ) --banking days
											OR ( LOWER ( p_part ) = 'ustd' AND us.isTradingDay ) --us trading days
											OR ( LOWER ( p_part ) = 'catd' AND ca.isTradingDay ) --ca trading days
											OR ( LOWER ( p_part ) = 'usbd' AND us.isBankingDay ) --us banking days
											OR ( LOWER ( p_part ) = 'cabd' AND ca.isBankingDay ) --ca banking days
											OR ( c.date = p_date )
											)
								) AS t )
					WHEN ( p_inc < 0 ) THEN
						( SELECT date[SAFE_OFFSET( ABS ( p_inc ) )]
							FROM (
									SELECT ARRAY_AGG ( date ORDER BY date DESC ) AS date
									FROM dataset_001.calendar AS c
									WHERE c.date BETWEEN DATE_ADD ( CAST ( p_date AS DATE ), INTERVAL -( ( ABS( p_inc ) * 2 ) + 5 ) DAY ) AND CAST ( p_date AS DATE )
										AND ( ( LOWER ( p_part ) = 'td' AND isTradingDay ) --trading days
											OR ( LOWER ( p_part ) = 'bd' AND isBankingDay ) --banking days
											OR ( LOWER ( p_part ) = 'ustd' AND us.isTradingDay ) --us trading days
											OR ( LOWER ( p_part ) = 'catd' AND ca.isTradingDay ) --ca trading days
											OR ( LOWER ( p_part ) = 'usbd' AND us.isBankingDay ) --us banking days
											OR ( LOWER ( p_part ) = 'cabd' AND ca.isBankingDay ) --ca banking days
											OR ( c.date = p_date )
											)
								) AS t )
					ELSE ( SELECT date
							FROM dataset_001.calendar AS c
							WHERE ( c.date = p_date )
								AND ( ( LOWER ( p_part ) = 'td' AND isTradingDay ) --trading days
									OR ( LOWER ( p_part ) = 'bd' AND isBankingDay ) --banking days
									OR ( LOWER ( p_part ) = 'ustd' AND us.isTradingDay ) --us trading days
									OR ( LOWER ( p_part ) = 'catd' AND ca.isTradingDay ) --ca trading days
									OR ( LOWER ( p_part ) = 'usbd' AND us.isBankingDay ) --us banking days
									OR ( LOWER ( p_part ) = 'cabd' AND ca.isBankingDay ) --ca banking days
									) )
				END
			WHEN p_part LIKE 'm' THEN
				DATE_ADD ( p_date, INTERVAL p_inc MONTH )
			WHEN p_part LIKE 'ms' THEN
				DATE_ADD ( CAST ( p_date AS DATETIME ), INTERVAL p_inc MILLISECOND )
			ELSE
				DATE_ADD ( p_date, INTERVAL p_inc DAY )
		END
);
```

###### What did you expect to see?
Query runs succesfully

###### What did you see instead?

The error is 

Feb 04, 2022 8:47:55 PM org.flywaydb.core.internal.jdbc.PlainExecutionTemplate error
SEVERE: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code!
Feb 04, 2022 8:47:55 PM org.flywaydb.commandline.Main error
SEVERE: Unexpected error
java.lang.StringIndexOutOfBoundsException: start 0, end -3, length 16
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(Unknown Source)
	at java.base/java.lang.AbstractStringBuilder.substring(Unknown Source)
	at java.base/java.lang.StringBuilder.substring(Unknown Source)
	at org.flywaydb.core.internal.util.StringUtils.trimOrPad(StringUtils.java:60)
	at org.flywaydb.core.internal.util.StringUtils.trimOrPad(StringUtils.java:40)
	at org.flywaydb.core.internal.util.AsciiTable.render(AsciiTable.java:95)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.outputQueryResult(DefaultSqlScriptExecutor.java:262)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleResults(DefaultSqlScriptExecutor.java:250)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:232)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:69)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:58)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:377)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
	at org.flywaydb.core.internal.jdbc.PlainExecutionTemplate.execute(PlainExecutionTemplate.java:41)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:214)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:273)
	at org.flywaydb.commandline.Main.main(Main.java:181)

**Comment by CharmanderJieniJieni** [comment]
Further narrowed the issue to be comment string `/*  ..... */`, nothing related to the attached script. The exception throws on `/*` and `*/`

**Comment by DoodleBobBuffPants** [comment]
Fixed by https://github.com/flyway/flyway/commit/b88f98037aa108058407f15467db429c589908d1

**Comment by CharmanderJieniJieni** [comment]
Thanks for the update, the issue still persists in version `8.5.12`. If I put below string it will hit same exception

```sql
--===============
```

**Comment by CharmanderJieniJieni** [comment]
@DoodleBobBuffPants should we reopen this?

**Comment by DoodleBobBuffPants** [comment]
Could you provide the exact SQL that causes the issue, as well as the output?

**Comment by CharmanderJieniJieni** [comment]
Sure, please see below

```sql
SET @@dataset_id = 'my_dataset';

BEGIN


CREATE TABLE IF NOT EXISTS `holiday`
(
  date DATE NOT NULL,
  us STRUCT<isTradingDay BOOL NOT NULL, isBankingDay BOOL NOT NULL, description STRING> NOT NULL,
  ca STRUCT<isTradingDay BOOL NOT NULL, isBankingDay BOOL NOT NULL, description STRING> NOT NULL,
  custom ARRAY<STRUCT<name STRING NOT NULL, isBusinessDay BOOL NOT NULL, description STRING>>
)
CLUSTER BY date;
INSERT INTO `holiday` ( date, us, ca )
VALUES
( '2015-01-01', ( FALSE, FALSE, 'New Year\'s Day' ), (  FALSE, FALSE, 'New Year\'s Day' ) ),
( '2015-12-25', ( FALSE, FALSE, 'Christmas' ), ( FALSE, FALSE, 'Christmas' ) ),
( '2016-01-01', ( FALSE, FALSE, 'New Year\'s Day' ), (  FALSE, FALSE, 'New Year\'s Day' ) ),
( '2016-12-25', ( FALSE, FALSE, 'Christmas' ), ( FALSE, FALSE, 'Christmas' ) ),
( '2017-01-01', ( FALSE, FALSE, 'New Year\'s Day' ), (  FALSE, FALSE, 'New Year\'s Day' ) ),
( '2017-12-25', ( FALSE, FALSE, 'Christmas' ), ( FALSE, FALSE, 'Christmas' ) );

END;
--====================================================================


```

**Comment by DoodleBobBuffPants** [comment]
The SQL you provided executes successfully for me

Could you share the output from Flyway that you are seeing and also add what you are expecting to see

**Comment by CharmanderJieniJieni** [comment]
Intersting, below is the execution output:

For Failed one
```sh
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 07, 2022 8:50:43 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: Flyway is up to date
Jun 07, 2022 8:50:43 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: Flyway Community Edition 8.5.12 by Redgate
Jun 07, 2022 8:50:43 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.12
Jun 07, 2022 8:50:43 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: 
Jun 07, 2022 8:50:43 PM org.flywaydb.core.internal.database.base.BaseDatabaseType info
INFO: Database: jdbc:bigquery://foo.iam.gserviceaccount.com;OAuthPvtKeyPath=sa.json;Timeout=60 (Google BigQuery 2.0)
Jun 07, 2022 8:50:43 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Join the GCP BigQuery beta via https://rd.gt/3fut40f
Jun 07, 2022 8:50:43 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: 
Jun 07, 2022 8:50:43 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Experiencing performance issues while using GCP BigQuery?
Jun 07, 2022 8:50:43 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Find out how Flyway Teams improves performance with batching at https://rd.gt/3CWAuTb
Jun 07, 2022 8:50:43 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: 
Jun 07, 2022 8:50:45 PM org.flywaydb.database.bigquery.BigQueryDatabase info
INFO: Google BigQuery databases have a 10 GB database size limit in Flyway Community Edition.
You have used 0 GB / 10 GB
Consider upgrading to Flyway Teams Edition for unlimited usage: https://rd.gt/3CWAuTb
Jun 07, 2022 8:50:50 PM org.flywaydb.core.internal.command.DbValidate info
INFO: Successfully validated 3 migrations (execution time 00:03.456s)
Jun 07, 2022 8:51:01 PM org.flywaydb.core.internal.command.DbMigrate info
INFO: Current version of schema `my_test_dataset`: 2
Jun 07, 2022 8:51:01 PM org.flywaydb.core.internal.command.DbMigrate warn
WARNING: outOfOrder mode is active. Migration of schema `my_test_dataset` may not be reproducible.
Jun 07, 2022 8:51:01 PM org.flywaydb.core.internal.command.DbMigrate info
INFO: Migrating schema `my_test_dataset` to version "3 - holiday" [non-transactional]
Jun 07, 2022 8:51:07 PM org.flywaydb.core.internal.jdbc.PlainExecutionTemplate error
SEVERE: Failed to execute operation in non-transactional context. Please restore backups and roll back database and code!
Jun 07, 2022 8:51:07 PM org.flywaydb.commandline.Main error
SEVERE: java.lang.StringIndexOutOfBoundsException: start 0, end -3, length 16
```

And then I removed the variable declaration and a successful one is like below:
```sh
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 07, 2022 8:58:06 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: Flyway is up to date
Jun 07, 2022 8:58:06 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: Flyway Community Edition 8.5.12 by Redgate
Jun 07, 2022 8:58:06 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.12
Jun 07, 2022 8:58:06 PM org.flywaydb.core.internal.license.VersionPrinter info
INFO: 
Jun 07, 2022 8:58:07 PM org.flywaydb.core.internal.database.base.BaseDatabaseType info
INFO: Database: jdbc:bigquery://foo.iam.gserviceaccount.com;OAuthPvtKeyPath=sa.json;Timeout=60 (Google BigQuery 2.0)
Jun 07, 2022 8:58:07 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Join the GCP BigQuery beta via https://rd.gt/3fut40f
Jun 07, 2022 8:58:07 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: 
Jun 07, 2022 8:58:07 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Experiencing performance issues while using GCP BigQuery?
Jun 07, 2022 8:58:07 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: Find out how Flyway Teams improves performance with batching at https://rd.gt/3CWAuTb
Jun 07, 2022 8:58:07 PM org.flywaydb.database.bigquery.BigQueryDatabaseType info
INFO: 
Jun 07, 2022 8:58:08 PM org.flywaydb.database.bigquery.BigQueryDatabase info
INFO: Google BigQuery databases have a 10 GB database size limit in Flyway Community Edition.
You have used 0 GB / 10 GB
Consider upgrading to Flyway Teams Edition for unlimited usage: https://rd.gt/3CWAuTb
Jun 07, 2022 8:58:15 PM org.flywaydb.commandline.Main info
INFO: Schema version: 3
Jun 07, 2022 8:58:15 PM org.flywaydb.commandline.Main info
INFO: 
Jun 07, 2022 8:58:15 PM org.flywaydb.commandline.Main info
INFO: +-----------+---------+-------------+------+---------------------+---------+
| Category  | Version | Description | Type | Installed On        | State   |
+-----------+---------+-------------+------+---------------------+---------+
| Versioned | 1       | holiday     | SQL  | 2022-06-07 19:17:27 | Missing |
| Versioned | 2       | holiday     | SQL  | 2022-06-07 19:26:19 | Missing |
| Versioned | 3       | holiday     | SQL  | 2022-06-07 20:57:39 | Success |
+-----------+---------+-------------+------+---------------------+---------+
```

**Comment by CharmanderJieniJieni** [comment]
I am using the docker image with JDBC driver from GCP by the way:

```dockerfile
FROM flyway/flyway:8.5.12

ENV PACKAGES="curl wget unzip dnsutils python3.8 python3-pip python3-setuptools python3-wheel gnupg git"

USER root
RUN apt-get update --allow-releaseinfo-change && \
    apt-get upgrade -y && \
    apt-get install -y ${PACKAGES} --no-install-recommends && \
    wget https://storage.googleapis.com/simba-bq-release/jdbc/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip -P drivers/ && \
    unzip drivers/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip -d drivers && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" |\
    tee -a /etc/apt/sources.list.d/google-cloud-sdk.list &&\
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - &&\
    apt-get update -y && apt-get install google-cloud-sdk -y &&\
    rm drivers/SimbaJDBCDriverforGoogleBigQuery42_1.2.21.1025.zip && \
    rm -rf /var/lib/apt/lists/* &&\

COPY flyway.conf /flyway/conf/flyway.conf
```

**Comment by DoodleBobBuffPants** [comment]
Apologies, I've just realized that while the fix was merged, it hasn't been released yet

It should be available in the next release which will be sometime in the next week
