### ISSUE TITLE
Flyway >=9.1.2 hanging forever on concurrent index creation

### ISSUE THREAD

**Issue by mihalyr** [flyway/flyway#3508]
###### Which version and edition of Flyway are you using?

works up to v9.0.4, breaks starting from v9.1.2 until v9.1.6 (latest)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven plugin

###### Which database are you using? (Type & version)

Tested on PostgreSQL 12.8, 13.8, 14.4

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Given a migration that contains:

```
CREATE INDEX CONCURRENTLY ...
```

Run the below

```
mvn flyway:migrate
```

###### What did you expect to see?

Migration completes successfully as with all versions below 9.1.2

###### What did you see instead?

Flyway hangs indefinitely at the non-transactional (create index concurrently) migration...

```
[INFO] Migrating schema "public" to version "3 - add indices to speed up querying" [non-transactional]
```

**Comment by mihalyr** [comment]
I suspect that this might be related to https://github.com/flyway/flyway/issues/2895 which was released in Flyway 9.1.2

The release notes say the following:

> Use transactional locks in PostgreSQL by default, which enables support for PgBouncer (session locks can be enabled again by setting `flyway.postgresql.transactional.lock=false`) 

I have also found a probably related issue https://github.com/flyway/flyway/issues/3492

**Comment by mihalyr** [comment]
How can I set `flyway.postgresql.transactional.lock=false` in Maven plugin?

**Comment by mihalyr** [comment]
Unfortunately, cannot setting [postgresqlTransactionalLock](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock) to `false` does not fix it. Still hanging forever

```
                        <configuration>
                            <driver>org.postgresql.Driver</driver>
                            <url>jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}</url>
                            <user>${postgres.user}</user>
                            <password>${postgres.password}</password>
                            <mixed>true</mixed>
                            <table>schema_version</table>
                            <connectRetries>30</connectRetries>
                            <cleanDisabled>false</cleanDisabled>
                            <pluginConfiguration>
                                <postgresqlTransactionalLock>false</postgresqlTransactionalLock>
                            </pluginConfiguration>
                        </configuration>
```

**Comment by mihalyr** [comment]
Hm, it seems the problem is with the Maven configuration, when I set `-Dflyway.postgresql.transactional.lock=false` on the command line, it works fine.

**Comment by mihalyr** [comment]
Could it be that the problem is how the Maven plugin constructs the configuration keys? 

See here https://github.com/flyway/flyway/blob/main/flyway-maven-plugin/src/main/java/org/flywaydb/maven/AbstractFlywayMojo.java#L899

```java
        String camelCaseRegex = "(?<!(^|[A-Z]))(?=[A-Z])|(?<!^)(?=[A-Z][a-z])";
        for (String key : pluginConfiguration.keySet()) {
            conf.put(FLYWAY_PLUGINS_PREFIX + String.join(".", key.split(camelCaseRegex)).toLowerCase(), pluginConfiguration.get(key));
        }
```

And look at the value of that constant here https://github.com/flyway/flyway/blob/main/flyway-core/src/main/java/org/flywaydb/core/internal/configuration/ConfigUtils.java#L113

```java
    public static final String FLYWAY_PLUGINS_PREFIX = "flyway.plugins.";
```

It looks like my configuration from above

```
                            <pluginConfiguration>
                                <postgresqlTransactionalLock>false</postgresqlTransactionalLock>
                            </pluginConfiguration>
```

would translate to `flyway.plugins.postgresql.transactional.lock` instead of `flyway.postgresql.transactional.lock`

Is this a bug in the code or in the [documentation](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock)?

**Comment by mihalyr** [comment]
My workaround currently is to set the property in Maven instead of the Flyway plugin configuration like this

```xml
    <properties>
        <!--
        Disable the transactional lock in Flyway that breaks all non-transactional migrations since v9.1.2 of the plugin
        See https://github.com/flyway/flyway/issues/3508
        -->
        <flyway.postgresql.transactional.lock>false</flyway.postgresql.transactional.lock>
    </properties>
```

**Comment by mihalyr** [comment]
Please note that this breaking change was introduced in a minor version without calling it out as a breaking change in the release notes, which mentions it as a "new feature". 

![image](https://user-images.githubusercontent.com/26523902/186660391-015634d3-c55a-4fad-b817-51f50d74e91b.png)

**Comment by Jojoooo1** [comment]
Any news on the subject ? Even when trying to use a conf file it hangs forever which is very problematic.

**Comment by AvaPL** [comment]
I've encountered the same problem today using Flyway 9.3.1. Here is my minimal example in Scala: https://github.com/AvaPL/flyway-postgres-concurrent-index-issue.

**Comment by bhavik-gandhi-0101** [comment]
- Solution is provided by flyway - https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock
- Tested out and its working. 
- I made the recommended changes as a part of flyway.conf and other solution is to make it part of individual SQL Script
ex: Say there is a SQL Script V1.011__CreatingIndex.sql, which has the SQL statement creating concurrent index, then create a file "V1.011__CreatingIndex.sql.conf" and the content of the conf file will be "flyway.postgresql.transactional.lock=false"

**Comment by OleKsimov** [comment]
Hi guys!
Are you by any chance going to fix this issue? 
That's kind of funny when someone uses your framework for a few years for big projects. And one day after the version update it just hangs. 40 days we are waiting for some fix, and there is no fix. Backward compatibility? Never heard of that. You should now configure additional properties to fix the issue in our new version. 
But why should we fix it from the user side? Maybe Flyway developers should set this property to false by default?

**Comment by Paxa** [comment]
It’s not a bug, it’s a feature (they said), now you can use pgbouncer any without additional configuration. (Yay)
Completely agree with you @OleKsimov, I wish I shouldn’t have spent those few hours to make it works again after upgrading

**Comment by bhavik-gandhi-0101** [comment]
> Hi guys! Are you by any chance going to fix this issue? That's kind of funny when someone uses your framework for a few years for big projects. And one day after the version update it just hangs. 40 days we are waiting for some fix, and there is no fix. Backward compatibility? Never heard of that. You should now configure additional properties to fix the issue in our new version. But why should we fix it from the user's side? Maybe Flyway developers should set this property to false by default? Do you understand that all migrations that create an index for Postgres database users can't be completed? Because using them without CONCURENTLY keyword on production env is just impossible.

Hi OleKsimov,

- Not associated with Flyway team, but have mentioned the solution above
- There is another solution which you can pass when calling flyway as command line "flyway.postgresql.transactional.lock"="false"
- Basically there are 3 solution provided
#1  - in Flyway.conf (mentioned in previous post)
#2  -  Command Line while calling flyway  (mentioned above)
#3  -  Per script (mentioned in previous post)

If you looking for flyway developers to change the default, is a separate discussion for them. There has to be some reason, why they change the default for which they should provide an explaination.

**Comment by OleKsimov** [comment]
@bhavik-gandhi-0101 

> If you looking for flyway developers to change the default, is a separate discussion for them. There has to be some reason, why they change the default for which they should provide an explaination.

Let me guess, the reason is that new versions of Flyway are just not working with the Postgres? Or maybe, just maybe because they changed the default 40 days ago and it broke backward compatibility? Why do developers who decided to use the Flyway have to justify themselves here and set up something urgently on their side a month later? Because PgBouncer and Spring are more popular than others? I've never seen such bad moves from dev teams before.

**Comment by mihalyr** [comment]
Hi there, I'm wondering if we should rename this issue to emphasize that the problem here is currently with the Maven plugin which does not take the configuration option as described in the documentation. See https://github.com/flyway/flyway/issues/3508#issuecomment-1227167053

The problem with the hanging itself can be fixed by setting the [transactional lock](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock) feature to `false` with one of the methods described in the documentation. The issue is that the Maven plugin configuration as described there does not work and my [workaround](https://github.com/flyway/flyway/issues/3508#issuecomment-1227170268) was to pass the name of the JVM property with Maven instead.

I expect one of two things to happen to resolve this issue:

1. Update documentation to reflect how to configure Maven in a way that works
2. Fix the Maven plugin to accept the variable as described in the documentation

My suggestion for the new issue title would be: "Flyway 9.1.2+ transactionalLock configuration not working in Maven plugin".
This issue is already marked with the `Maven` tag/label, so I think the Flyway devs are also tracking only the Maven plugin config issue here.

**Comment by Paxa** [comment]
I think most of us ended up here because after bumping version we expect it continue to work, but it didn't.

If I understand correctly, starting from version 9.1.2 default configuration works for pgbouncer, but not for plain postgresql server

**Comment by OleKsimov** [comment]
@mihalyr 
`Hi there, I'm wondering if we should rename this issue to emphasize that the problem here is currently with the Maven plugin which does not take the configuration option as described in the documentation`

I use Quarkus with Gradle plugin, and I can't configure mentioned property in [suggested](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock#usage) ways. It's just not working, even using ENV variable. We already have env variables configured in project, for example for testcontainers, so it's quite strange that FLYWAY_POSTGRESQL_TRANSACTIONAL_LOCK=false not working.
I'll try to discuss the problem with Quarkus team to allow setting this property in configuration.

**Comment by mihalyr** [comment]
Sorry guys, I opened this issue because I had the same problem as all of you, the Flyway team provided a solution, which did not work with the Maven plugin, so my remaining problem was only on setting this in the Maven plugin. 

I have no idea about Gradle or all the other ways, but here one commenter confirmed that the documented way of setting the Gradle property worked for them https://github.com/flyway/flyway/issues/3508#issuecomment-1258504525

I am fine if you want to use this issue for the generic problem of changing the default value. I was just concerned that my problem with the Maven plugin got buried under all the other discussions about non-Maven issues. Maybe I should create a separate issue for the Maven plugin then if this remains the generic one...

**Comment by sigand** [comment]
Spring Boot workaround:
https://github.com/spring-projects/spring-boot/issues/32629

**Comment by NJAldwin** [comment]
For some reason, none of the proposed solutions were working for me (they stopped the hanging, but introduced other issues instead).

Instead, I found that I could change my migration to prefix it with `NT` e.g. `V123__some_migration.sql` --> `NTV123__some_migration.sql`.  This invokes the magic non-transactional resolver from #1027

Hope this helps anyone seeing the same behavior.

[Source on SO](https://stackoverflow.com/a/32271558)

**Comment by jbhurruth** [comment]
@NJAldwin Which version are you using? For me, prefixing filenames with `NT` just leads to them being ignored and a message saying `1 SQL migrations were detected but not run because they did not follow the filename convention.`

**Comment by ali-adnan-careem** [comment]
> * Solution is provided by flyway - https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock
> * Tested out and its working.
> * I made the recommended changes as a part of flyway.conf and other solution is to make it part of individual SQL Script
>   ex: Say there is a SQL Script V1.011__CreatingIndex.sql, which has the SQL statement creating concurrent index, then create a file "V1.011__CreatingIndex.sql.conf" and the content of the conf file will be "flyway.postgresql.transactional.lock=false"

does not work for me .. using for flyway v9.15.2. it gives following error: 
`org.flywaydb.core.api.FlywayException: Unknown configuration property: flyway.postgresql.transactional.lock`

**Comment by RomanAbakumovMH** [comment]
SpringBoot3.0.3 & flyway 9.5.1
Configuration properties are not working, looks like the appropriate config provider is missing, I was able to achieve what is needed by adding provider like:

'public class PostgreSQLConfigurationProvider implements ConfigurationProvider<PostgreSQLConfigurationExtension> {
    @Override
    public Map<String, String> getConfiguration(PostgreSQLConfigurationExtension configurationExtension, ClassicConfiguration flywayConfiguration) throws Exception {
        return Collections.singletonMap("flyway.postgresql.transactional.lock", "false");
    }

    @Override
    public Class getConfigurationExtensionClass() {
        return PostgreSQLConfigurationExtension.class;
    }
}
`

It would be nice to add support for default property type configuration.
in spring boot setting flyway.postgresql.transactional.lock or spring.flyway.postgresql.transactional.lock to false doesn't have any effect.
Tested the same on the latest version of flyway/spring boot, same behavior.

**Comment by flaviut** [comment]
I don't understand any of this configuration stuff, but I've been able to fix this for myself with the following code:

```
import org.flywaydb.core.api.configuration.FluentConfiguration
import org.springframework.boot.autoconfigure.flyway.FlywayConfigurationCustomizer
import org.springframework.context.annotation.Configuration

@Configuration
class FlywayConfig : FlywayConfigurationCustomizer {
    override fun customize(configuration: FluentConfiguration) {
        // Disable the transactional lock in Flyway that breaks all non-transactional migrations since v9.1.2 of the plugin
        // See https://github.com/flyway/flyway/issues/3508
        configuration.configuration(
            mapOf(
                "flyway.postgresql.transactional.lock" to "false",
            )
        )
    }
}
```

**Comment by koriit-kontakt** [comment]
Happened to us today. Before we found this thread, we figured out that flyway's main session is running in a transaction and acquires a shared lock (doing simple select already does it) on a bunch of `pg_*` tables, one of which blocks our migration session with create index concurrently:

```
pg_namespace_oid_index
pg_namespace_nspname_index
pg_class_tblspc_relfilenode_index
pg_class_relname_nsp_index
pg_class_oid_index
pg_namespace
pg_class
```

**Comment by JasonLuo-Redgate** [comment]
This issue should have been fixed in the latest version of Flyway.
Refer to https://github.com/flyway/flyway/issues/3682

**Comment by MrMaxxan** [comment]
I've tried with this previous minimal example and changing Flyway version to 9.19.4 or 9.21.1, but it still hangs when creating the index. Is there anything else that needs to be done to make it work?
https://github.com/AvaPL/flyway-postgres-concurrent-index-issue

**Comment by froque** [comment]
@MrMaxxan you need to disable the Postgresql transactional lock behaviour 
```diff
diff --git a/src/main/scala/Main.scala b/src/main/scala/Main.scala
index 5609318..7b934b0 100644
--- a/src/main/scala/Main.scala
+++ b/src/main/scala/Main.scala
@@ -10,6 +10,7 @@ object Main extends App {
 
   val flyway = Flyway
     .configure()
+    .configuration(java.util.Map.of("flyway.postgresql.transactional.lock","false"))
     .dataSource(dataSource)
     .load()
```

**Comment by Klassen-Olga** [comment]
This works for gradle
spring:
  flyway:
     postgresql:
        transactional-lock: false

**Comment by joschi** [comment]
@Klassen-Olga Please note that this configuration setting is only available in Spring Boot 3.2.0 and later.
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#miscellaneous

**Comment by topEngineerRay** [comment]
None of the above works for me: spring boot 3.2 + flyway 9.22.3

**Comment by jiachenliucc** [comment]
> I don't understand any of this configuration stuff, but I've been able to fix this for myself with the following code:
> 
> ```
> import org.flywaydb.core.api.configuration.FluentConfiguration
> import org.springframework.boot.autoconfigure.flyway.FlywayConfigurationCustomizer
> import org.springframework.context.annotation.Configuration
> 
> @Configuration
> class FlywayConfig : FlywayConfigurationCustomizer {
>     override fun customize(configuration: FluentConfiguration) {
>         // Disable the transactional lock in Flyway that breaks all non-transactional migrations since v9.1.2 of the plugin
>         // See https://github.com/flyway/flyway/issues/3508
>         configuration.configuration(
>             mapOf(
>                 "flyway.postgresql.transactional.lock" to "false",
>             )
>         )
>     }
> }
> ```

thank you, i try this way not ok, but i found this is work for me. (**Spring boot 3.1.0 and Flyway 9.16.3**)
[For flyway >= 9.1.2, it tries to be compatible with pgbouncer by default, and creating concurrent index will hang the process.](https://stackoverflow.com/a/73928224)

```
...
flywayConfiguration.getPluginRegister()
        .getPlugin(PostgreSQLConfigurationExtension.class)
        .setTransactionalLock(false);
Flyway flyway = flywayConfiguration.load();
...
```

**Comment by ayush-finix** [comment]
> any ideas how to set `flyway.postgresql.transactional.lock` with gradle?
> 
> Update, worked like this:
> 
> ```groovy-gradle
> flyway {
>     pluginConfiguration = [
>         postgresqlTransactionalLock: "false"
>     ]
>     //...
> }
> ```

This doesn't work for me 
```
plugins {
    id "org.flywaydb.flyway" version "10.10.0"
}

flyway {
    pluginConfiguration = [
            postgresqlTransactionalLock: 'false'
    ]
}
```
With error 
```
* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Unknown configuration property: flyway.plugins.postgresql.transactional.lock
```
I see the property also being prefixed with flyway.plugins

**Comment by albertscholtz** [comment]
After trying and failing on the Gradle and Spring properties related suggestions I had to create a custom Flyway bean, which was successful. [Gist](https://gist.github.com/albertscholtz/3ffb91205d81ca8e3d3f8cc069e58cc1)

Using Spring Boot 3.2.4 and Flyway 10.11.0. I'm guessing it depends whether flyway is run from the Gradle plugin or spring boot app during startup which solution will have the desired effect.

**Comment by EarthCitizen** [comment]
The `FlywayConfigurationCustomizer` worked for me. Spring Boot 3.1.x.

**Comment by Kevin-Breidenbach-Engine** [comment]
For anyone using Scala I was able to simply do this to get it to work

(the `configuration(Map("flyway.postgresql.transactional.lock" -> "false").asJava)` is the line that fixed it)

```scala
 Flyway
   .configure()
   .baselineOnMigrate(true)
   .locations("classpath:sql")
   .dataSource(url, username.value, password.value)
   .configuration(Map("flyway.postgresql.transactional.lock" -> "false").asJava)
   .loggers("slf4j")
   .load()
   .migrate()
```
