### ISSUE TITLE
The group parameter does not work as expected

### ISSUE THREAD

**Issue by gaborcs** [flyway/flyway#3671]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 9.17.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
The official Docker image

###### Which database are you using? (Type & version)
PostgreSQL 15.1

###### Which operating system are you using?
Linux containers on macOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I created a versioned migration, an afterVersioned callback, and two repeatable migrations. I made a syntax error in the second repeatable migration. I ran the migration with the group parameter set to true, and all other relevant parameters left at their default values.

###### What did you expect to see?
I expected the versioned migration, the afterVersioned callback, and the repeatable migrations to run as a single transaction, and therefore get rolled back when the failure happens.

###### What did you see instead?
The repeatable migrations were rolled back, but everything else stayed. This means the DB migration can result in a broken DB schema, because the tables are modified, but the functions and views created by repeatable migrations are not updated.

###### Further information
- If I delete the afterVersioned callback, the versioned and repeatable migrations run in a single transaction, as expected. There's nothing special in my afterVersioned callback, just a `CREATE OR REPLACE FUNCTION`.
- Having only afterVersioned callbacks instead of repeatable migrations behaves similarly. The afterVersioned callbacks are not part of the transaction, even though I'd expect them to be. (Ideally, I want to use afterVersioned callbacks instead of repeatable migrations, since they don't require having `${flyway:timestamp}` placeholders on the top of each file to make sure they run every time, and deleting them doesn't result in an error because of the missing migration.)

**Comment by JasonLuo-Redgate** [comment]
Hi @gaborcs , after some investigation, we confirmed that this was a bug caused by the way how an event handler runs (like afterVersioned in this case), it may break a ongoing transaction. This was fixed and will be included in the next release.

**Comment by gaborcs** [comment]
Awesome, I'm looking forward to the release.

**Comment by gaborcs** [comment]
Hi @JasonLuo-Redgate! Unfortunately, I just tested this with the latest version of Flyway (9.20.1), and the issue still seems to be present.

**Comment by JasonLuo-Redgate** [comment]
Hi @gaborcs , I locally tested in my environment, and it worked fine. Here are the details How I locally verified this issue:

Set `flyway.group=true` in .conf.

Put 3 .sql files:
- V1__first.sql
- R__repeatable.sql  (Put something wrong in it to make it fail)
- afterVersioned.sql

Run Flyway with PostgreSQL 15.2. 

The rollback happened as expected, the change in `V1__first.sql ` didn't apply to the database. 
 
Could you help confirm whether my local verification matches the expected scenario?

**Comment by JasonLuo-Redgate** [comment]
Hi @gaborcs , `group `is used to group all pending migrations together in the same transaction. 
But Callbacks are not part of it unfortunately.
Based on current design, a callback event will trigger a separately commit instantly.

**Comment by gaborcs** [comment]
I see. Thank you for the information.
