### ISSUE TITLE
Error setting current schema to "public"

### ISSUE THREAD

**Issue by gnomff** [flyway/flyway#995]
With the following settings in flyway-gradle-plugin version 3.2.1

flyway{
    url = "jdbc:h2:mem;MODE=MySQL"
    user = "sa"
    schemas = ["PUBLIC"]
}
I get the following error: Error setting current schema to "public"

What was strange about this error was when I turned on debug I could see the PUBLIC schema get populated with the schema_version table and the migrations ran without error. The plugin reported the error *after* running almost to completion. 

Tacking INIT=CREATE SCHEMA IF NOT EXISTS "public" to the end of the url worked as a work around.

**Comment by axelfontaine** [comment]
There are still some issues with h2 and the various db compatibility modes. In the future we want to provide the possibility to override the db autodetection with a specific db type, which would most likely fix this.

**Comment by gnomff** [comment]
Thanks for getting back to me, I look forward to the fix!

**Comment by axelfontaine** [comment]
This was fixed as part of changes on how we read and set the current schema.

**Comment by hieuduy** [comment]
Hi @axelfontaine,

Using on H2 DB, my application is running through all migration scripts successfully.
But I'm still experiencing in this issue. here below is my snippet code:

```java
        Flyway flyway = new Flyway();
        flyway.setDataSource(String.format("jdbc:h2:%s;IFEXISTS=TRUE;MODE=MySQL;FILE_LOCK=NO", dbLocation), "sa", null);
        flyway.setSchemas("main");
        flyway.repair();
        flyway.migrate();
        // After the migration was completed then try setting back the particular schemas
        // to avoid the exception but it's still there
        flyway.setSchemas("public", "PUBLIC");
        flyway.baseline(); 
```
```Exception
        org.flywaydb.core.api.FlywayException: Error setting current schema to "public"
```
The current version:
- H2 DB: 1.4.193 (Embedded)
- Flyway: 4.0.3

I'm appreciated in your help.
