### ISSUE TITLE
ClassCastException in PostgreSQLDbSupport.executePgCopy when using BasicDataSource

### ISSUE THREAD

**Issue by jensberke** [flyway/flyway#999]
Hi,

I get the following class cast exception with Flyway 3.2.1 when a COPY statement is used in a migration:

Caused by: java.lang.ClassCastException: org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper cannot be cast to org.postgresql.core.BaseConnection
	at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:110)
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:112)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:284)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:282)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:282)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)

The datasource used by the Flyway instance is one defined as a resource in a context.xml of a Tomcat 7 installation, like this:

  <Resource
    factory="org.apache.tomcat.dbcp.dbcp.BasicDataSourceFactory"
    name="jdbc/mydatabase"
    auth="Container"
    type="javax.sql.DataSource"
    username="USERNAME"
    password="PASSWORD"
    driverClassName="org.postgresql.Driver"
    url="URL" />

That datasource is fetched via JDNI and then used for the Flyway instance.

The reason for the class cast exception is that the a org.apache.tomcat.dbcp.dbcp.BasicDataSource creates a connection instance of class org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper, which is not a BaseConnection.

This has been introduced with #863.

I know it's easy to get  around this by switching to another kind of datasource for the Flyway migrations. But Flyway should probably address a case like this by making an "instanceof BaseConnection" check and exit with a more explanatory exception message if the connections is not the expected class.

Regards
Jens

**Comment by axelfontaine** [comment]
Thanks for the report. I guess ```Connection.isWrapperFor()``` would be a good starting point. Can you find out how the connection is wrapped exactly in your case. I'd much rather have a working solution than an error message for this.

Cheers
Axel

**Comment by jensberke** [comment]
connection.isWrapperFor(org.postgresql.core.BaseConnection.class) returns "true"

The connections are wrapped like this:

connection.unwrap(Connection.class) returns a org.apache.tomcat.dbcp.dbcp.PoolingDataSource$PoolGuardConnectionWrapper

PoolGuardConnectionWrapper.getDelegate() returns a org.apache.tomcat.dbcp.dbcp.PoolableConnection 

PoolableConnection.getDelegate()  returns a org.postgresql.jdbc4.Jdbc4Connection

**Comment by axelfontaine** [comment]
Maybe connection.unwrap(BaseConnection.class) could do the trick. Could you try this and see if it works?

**Comment by jensberke** [comment]
It does! :)

**Comment by axelfontaine** [comment]
Bingo! Then let's go for that! Would you like to submit a quick PR?

**Comment by jensberke** [comment]
I can't do it quickly right now, because I don't have the Flyway project and git set up here (I had simply debugged my project which includes the Flyway source jar and made an inspection of "connection.unwrap(BaseConnection.class)" on a debug breakpoint in PostgreSQLDbSupport.executePgCopy).

**Comment by axelfontaine** [comment]
Fixed with PR

**Comment by schmitch** [comment]
@axelfontaine I still get that exception (maybe its because of hikaricp)
```
- should give status 200 no matter what *** FAILED ***
[info]   java.lang.ClassCastException: com.sun.proxy.$Proxy21 cannot be cast to org.postgresql.core.BaseConnection
[info]   at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:138)
[info]   at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:112)
[info]   at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
[info]   at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
[info]   at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
[info]   at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
[info]   at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
[info]   at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
[info]   at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
[info]   at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
[info]   ...

```

**Comment by schmitch** [comment]
Actually it won't fix my problem, but the 100% correct way of getting a `CopyManager` (https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/postgresql/PostgreSQLDbSupport.java#L147) is:

```
CopyManager copyManager = connection.unwrap(PGConnection.class).getCopyAPI()
```
